CREATE   VIEW [Silver].[vPurchaseOrder]
AS
WITH RankedPurchaseOrder AS (
    SELECT 
        systemId AS PurchaseOrderID,
        UPPER(LTRIM(RTRIM([no]))) AS PurchaseOrderNumber,
        UPPER(LTRIM(RTRIM(buyFromVendorNo))) AS VendorNumber,
        UPPER(LTRIM(RTRIM(vendorInvoiceNo))) AS VendorInvoiceNumber,
        yourReference AS PurchaseOrderReference,
        currencyCode AS Currency,
        paymentTermsCode AS PaymentTerms,
        UPPER(LTRIM(RTRIM(wsI0042ProNo))) AS ProNumber,
        UPPER(LTRIM(RTRIM(wsI0042BoLNo))) AS BillOfLandingNumber,
        UPPER(LTRIM(RTRIM(wsI0042ContainerNo))) AS ContainerNumber,
        UPPER(LTRIM(RTRIM(wsI0042SealNo))) AS SealNumber,
        UPPER(LTRIM(RTRIM(locationCode))) AS ShippingLocation,
        UPPER(LTRIM(RTRIM(wsI0042ShippingAgent))) AS ShippingAgent,
        UPPER(LTRIM(RTRIM(shipmentMethodCode))) AS ShipmentMethod,
        status AS Status,
        amount AS Amount,
        amountIncludingVAT AS AmountWithTaxes,
        wsI0032TotalCubage AS TotalCubage,
        wsI0032TotalWeight AS TotalWeight,
        orderDate AS OrderDate,
        documentDate AS DocumentDate,
        dueDate AS DueDate,
        postingDate AS PostingDate,
        expectedReceiptDate AS ExpectedReceiptDate,
        systemCreatedBy AS CreatedByUserID,
        systemCreatedAt AS CreatedOn,
        CAST(systemCreatedAt AS DATE) AS CreatedOnDate,
        systemModifiedBy AS LastUpdatedByUserID,
        systemModifiedAt AS LastUpdated,
        CAST(systemModifiedAt AS DATE) AS LastUpdatedDate,
        ROW_NUMBER() OVER (PARTITION BY systemId ORDER BY systemModifiedAt DESC) AS rn
    FROM [DE_LH_100_BRONZE_WoodlandMills].[dbo].[PurchaseOrder]
),
RankedPurchaseOrderLine AS (
    SELECT 
        systemId AS PurchaseOrderLineID,
        UPPER(LTRIM(RTRIM(documentNo))) AS PurchaseOrderNumber,
        UPPER(LTRIM(RTRIM([no]))) AS ItemNumber,
        UPPER(LTRIM(RTRIM(type))) AS LineType,
        quantity AS LineQuantity,
        UPPER(LTRIM(RTRIM(locationCode))) AS LineShippingLocation,
        dropShipment AS DropShipment,
        lineAmount AS LineAmount,
        lineDiscount AS LineDiscount,
        lineDiscountAmount AS LineDiscountAmount,
        directUnitCost AS LineCost,
        qtyToReceive AS QuantityToReceive,
        quantityReceived AS QuantityReceived,
        qtyToInvoice AS QuantityToInvoice,
        quantityInvoiced AS QuantityInvoiced,
        leadTimeCalculation AS LeadTimeCalculation,
        orderDate AS LineOrderDate,
        expectedReceiptDate AS LineExpectedReceiptDate,
        systemCreatedBy AS LineCreatedByUserID,
        systemCreatedAt AS LineCreatedOn,
        CAST(systemCreatedAt AS DATE) AS LineCreatedOnDate,
        systemModifiedBy AS LineLastUpdatedByUserID,
        systemModifiedAt AS LineLastUpdated,
        CAST(systemModifiedAt AS DATE) AS LineLastUpdatedDate,
        ROW_NUMBER() OVER (PARTITION BY systemId ORDER BY systemModifiedAt DESC) AS rn
    FROM [DE_LH_100_BRONZE_WoodlandMills].[dbo].[PurchaseOrderLine]
)
SELECT
    rpo.PurchaseOrderID,
    rpo.PurchaseOrderNumber,
    rpo.VendorNumber,
    rpo.VendorInvoiceNumber,
    rpo.PurchaseOrderReference,
    rpo.Currency,
    rpo.PaymentTerms,
    rpo.ProNumber,
    rpo.BillOfLandingNumber,
    rpo.ContainerNumber,
    rpo.SealNumber,
    rpo.ShippingLocation,
    rpo.ShippingAgent,
    rpo.ShipmentMethod,
    rpo.Status,
    rpo.Amount,
    rpo.AmountWithTaxes,
    rpo.TotalCubage,
    rpo.TotalWeight,
    rpo.OrderDate,
    rpo.DocumentDate,
    rpo.DueDate,
    rpo.PostingDate,
    rpo.ExpectedReceiptDate,
    rpo.CreatedByUserID,
    rpo.CreatedOn,
    rpo.CreatedOnDate,
    rpo.LastUpdatedByUserID,
    CASE WHEN rpo.[LastUpdated] > rpol.LineLastUpdated THEN rpo.[LastUpdated] ELSE rpol.LineLastUpdated END AS LastUpdated,
    CASE WHEN rpo.[LastUpdatedDate] > rpol.LineLastUpdatedDate THEN rpo.[LastUpdatedDate] ELSE rpol.LineLastUpdatedDate END AS LastUpdatedDate,
    rpol.PurchaseOrderLineID,
    rpol.ItemNumber,
    rpol.LineType,
    rpol.LineQuantity,
    rpol.LineShippingLocation,
    rpol.DropShipment,
    rpol.LineAmount,
    rpol.LineDiscount,
    rpol.LineDiscountAmount,
    rpol.LineCost,
    rpol.QuantityToReceive,
    rpol.QuantityReceived,
    rpol.QuantityToInvoice,
    rpol.QuantityInvoiced,
    rpol.LeadTimeCalculation,
    rpol.LineOrderDate,
    rpol.LineExpectedReceiptDate,
    rpol.LineCreatedByUserID,
    rpol.LineCreatedOn,
    rpol.LineCreatedOnDate,
    rpol.LineLastUpdatedByUserID,
    rpol.LineLastUpdated,
    rpol.LineLastUpdatedDate
FROM RankedPurchaseOrder rpo
LEFT JOIN RankedPurchaseOrderLine rpol ON rpo.PurchaseOrderNumber = rpol.PurchaseOrderNumber
WHERE rpo.rn = 1 AND rpol.rn = 1